spring:
  datasource:
    url: jdbc:h2:mem:community
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true